name: 'Power BI Service Upload'
description: 'Deploys PBIX and RDL Files to the Power BI Service'
author: 'Mohit Nayar'
inputs:
  files:
    description: 'Files to deploy'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
      - ${{ inputs.files }}
